### ISSUE TITLE
RGB2Depth

### ISSUE THREAD

**Issue by fzd9752** [createamind/busyplan#5]
目的：验证现有模型预测深度的可靠性，为是否进一步改良模型提供依据。

- [x] Quantitative Evaluation, 量化方法，与其他方式对比
重现已有模型，根据评估误差横向评估
需要输出图像达到256x256

2.- [ ] Deeper Depth Prediction with Fully Convolutional Residual Networks  upsampling to 640x480
https://arxiv.org/pdf/1606.00373.pdf
https://github.com/iro-cp/FCRN-DepthPrediction  代码不完整

4.Learning Depth from Single Monocular Images Using Deep Convolutional Neural Fields  https://arxiv.org/pdf/1502.07411.pdf

6.Single-Image Depth Perception in the Wild
https://arxiv.org/pdf/1604.03901.pdf   
https://github.com/wfchen-umich/relative_depth 
7.Multi-Scale Continuous CRFs as Sequential Deep Networks for Monocular Depth Estimation
https://arxiv.org/pdf/1704.02157.pdf
https://github.com/danxuhk/ContinuousCRF-CNN
选用
- [ ] http://perso.ensta-paristech.fr/%7Epinard/depthnet/    1/4 downsampling，缺失训练代码，可以预测
https://hal.archives-ouvertes.fr/hal-01587652/document
https://github.com/ClementPinard/DepthNet
- [ ] Depth Map Prediction from a Single Image using a Multi-Scale Deep Network   输出74x75  ,提供评估方法 https://www.cs.nyu.edu/~deigen/depth/
https://github.com/MasazI/cnn_depth_tensorflow 不完整
https://github.com/janivanecky/Depth-Estimation  caffe

- [x] Qualitative Evaluation，质化方法，点云图像化展示
depth to （x,y,z)点云array  快速转换：https://codereview.stackexchange.com/questions/79032/generating-a-3d-point-cloud
点云可视化
https://github.com/daavoo/pyntcloud
https://github.com/createamind/busyplan/blob/master/zhangwei/point_cloud.ipynb

**Comment by fzd9752** [comment]
深度图point cloud可视化：
[ ] 深度 - > 点云
[ ] matplotlib or rviz 可视化

RVIZ - http://gazebosim.org/tutorials?tut=drcsim_visualization&cat=

**Comment by waxz** [comment]
优化模型的方法
1、深度分割联合预测
http://users.eecs.northwestern.edu/~xsh835/assets/cvpr2015_depth.pdf

**Comment by zdx3578** [comment]
result show  https://mp.weixin.qq.com/s?__biz=MzA5MDMwMTIyNQ==&mid=2649292578&idx=1&sn=ee9c909ef5d8000c821df48f2b006a46&chksm=8811e964bf666072622f38346dcba98d373a546db1187fb6948abea45357adeaa6dcaee9f580&scene=21#wechat_redirect
